[project]
name = "kioto"
version = "2.4.1"
description = "Standard library for Mire"
entry = "code/mod.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0

[paths]
sources = "."
tests = "tests"
output = "bin"
cache = "bin/.cache"

[exports]
strings = "core/strings"
lists   = "core/lists"
dicts   = "core/dicts"
time    = "core/time"
fs      = "core/fs"
env     = "core/env"
proc    = "core/proc"
async   = "core/async"
mem     = "core/mem"
cpu     = "core/cpu"
math    = "core/math"
net     = "core/net"
log     = "core/log"
cli     = "core/cli"
crypto  = "core/crypto"
